language: python
python:
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
# command to install dependencies
install: "pip install -r tests/test_requirements.txt"
# command to run tests
script: py.test tests/*.py
virtualenv:
    system_site_packages: true
